name: flutter_ffi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  ffigen: ^9.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


ffigen:
  output: 'lib/ffigen.dart'
  headers:
    entry-points:
      - 'rust_lib/example.h'